<a href="https://colab.research.google.com/github/sevensixteeeen/NumPy-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# indexing
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,0])

7


In [ ]:
#slicing
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
# From the second element, slice elements from index 0 to index 3 (not included):
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:3])

[6 7 8]


In [ ]:
#from both element, return index 2;
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6 7]
int32


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# randam decimal number
np.random.rand(4,2,3)

array([[[0.55782714, 0.74977309, 0.28908597],
        [0.74006608, 0.86202627, 0.88936922]],

       [[0.99805967, 0.29167891, 0.04199726],
        [0.29679805, 0.17034416, 0.68543404]],

       [[0.02475669, 0.84664349, 0.18380896],
        [0.87809576, 0.48604735, 0.33587806]],

       [[0.46283289, 0.38093634, 0.54753867],
        [0.78048254, 0.20872368, 0.84215272]]])

In [ ]:
# randam integer number
np.random.randint(7,9,size=[3,6])

array([[8, 7, 8, 8, 7, 7],
       [7, 7, 8, 7, 8, 7],
       [8, 8, 8, 8, 8, 7]])

In [ ]:
np.random.randint(7,9)

8

In [ ]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat on array
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
op = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
op[1:4,1:4]=z
print(op)
print(op.ndim)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
2


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

3


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# dimension of an array
arr_1d = np.array([1, 2, 3])
print(f"Dimension of arr_1d: {arr_1d.ndim}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimension of arr_2d: {arr_2d.ndim}")

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr_3d: {arr_3d.ndim}")

Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3


In [ ]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array:",arr.shape)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(2,3,2)
print(narr)
print("dimension ",narr.ndim,"from ",arr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimension  3 from  1


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],)
print(arr,"dimension of an array=",arr.ndim)
narr = arr.reshape(6,5)
print(narr)
narr[[0,4,5],3:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] dimension of an array= 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")
for x in np.nditer(arr[:, ::2]):
  print(x)

Dimension of arr: 2
Shape of arr: (2, 4)
1
3
5
7


In [ ]:
# vstack()  to stack along rows.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
# vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
# dstack() to stack along height
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# array_split()
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr.shape)

(6, 2)


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
## sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [ ]:
## sorting string
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [ ]:
# sorting 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [ ]:
## filter array that will return only values higher than 42

arr=np.array([42,41,52,2,56,46])

filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, False, True, True]
[52 56 46]


In [ ]:
# filter array that will return only even elements

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array

In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
## random integer from 1 to 100:
from numpy import random
x = random.randint(100)
print(x)

89


In [ ]:
## random float from 0 to 1:
from numpy import random
x=random.rand()
print(x)

0.6002970544868286


In [ ]:
## 1-D array containing 5 random integers from 0 to 100:
x=random.randint(0,100,size=5)
print(x)

[59 74 68 37 11]


In [ ]:
## 2D  array
x=random.randint(0,100,size=(3,5))
print(x)

[[28 87 67 74 48]
 [49 18 50 17 43]
 [27 22 95  0 22]]


In [ ]:
## 3-D array
x=random.randint(0,100,size=(3,4,6))
print(x)
print("demintion of a array",x.ndim)

[[[87 98 99 77 85 13]
  [ 3 61  9 87 50 89]
  [60 22 35 50 63  0]
  [80 94 63 46 97 78]]

 [[ 0 96  4 50 44 78]
  [68 38  8 30 10 45]
  [40 12 92  8 92 49]
  [76 28 42 99 65 35]]

 [[26 12 72 44 78 77]
  [67 84 85 34 99 58]
  [43 40 52  8 54 12]
  [87 31 67 14 80 18]]]
demintion of a array 3


In [ ]:
## 1-D array containing 5 random floats:
x=random.rand(5)
print(x)

[0.51859612 0.1235549  0.63592363 0.64639077 0.54972363]


In [ ]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 3 7 7 7 3 7 3 7 7 5 7 7 7 7 5 7 5 7 7 7 7 7 7 7 7 3 7 7 5 7 7 7 7 7 5 7
 3 7 7 5 7 7 7 3 5 7 5 5 7 5 7 5 5 5 7 5 7 5 7 7 7 7 7 3 5 7 5 7 7 7 5 7 7
 7 3 7 7 7 5 7 7 7 7 7 7 5 7 7 5 5 5 5 7 7 5 7 3 7 7]


In [ ]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]


np.int64(499128)

In [ ]:
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [ ]:
my_array = np.array([[[[1,3,4]]]])
np.array(my_array, ndmin=5)

array([[[[[1, 3, 4]]]]])