<a href="https://colab.research.google.com/github/sevensixteeeen/NumPy-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [44]:
# indexing
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,0])

7


In [45]:
#slicing
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [46]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [47]:
# From the second element, slice elements from index 0 to index 3 (not included):
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:3])

[6 7 8]


In [48]:
#from both element, return index 2;
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [49]:
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [50]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6 7]
int32


In [51]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [53]:
# randam decimal number
np.random.rand(4,2,3)

array([[[0.63926164, 0.84058835, 0.79901164],
        [0.74469637, 0.40076766, 0.82928543]],

       [[0.54145687, 0.65977439, 0.32164697],
        [0.41693643, 0.38401158, 0.78615402]],

       [[0.98114841, 0.59976901, 0.24300562],
        [0.09191418, 0.24658385, 0.37876987]],

       [[0.30660845, 0.1748225 , 0.86164106],
        [0.0821    , 0.4144838 , 0.29938776]]])

In [54]:
# randam integer number
np.random.randint(7,9,size=[3,6])

array([[8, 8, 7, 8, 8, 8],
       [8, 8, 8, 8, 7, 7],
       [8, 8, 8, 8, 8, 7]])

In [55]:
np.random.randint(7,9)

7

In [56]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# repeat on array
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [58]:
op = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
op[1:4,1:4]=z
print(op)
print(op.ndim)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
2


In [59]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

3


In [60]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [61]:
# dimension of an array
arr_1d = np.array([1, 2, 3])
print(f"Dimension of arr_1d: {arr_1d.ndim}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimension of arr_2d: {arr_2d.ndim}")

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr_3d: {arr_3d.ndim}")

Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3


In [62]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array:",arr.shape)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(2,3,2)
print(narr)
print("dimension ",narr.ndim,"from ",arr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimension  3 from  1


In [64]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],)
print(arr,"dimension of an array=",arr.ndim)
narr = arr.reshape(6,5)
print(narr)
narr[[0,4,5],3:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] dimension of an array= 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [65]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [66]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [67]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [68]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [69]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [70]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")
for x in np.nditer(arr[:, ::2]):
  print(x)

Dimension of arr: 2
Shape of arr: (2, 4)
1
3
5
7


In [71]:
# vstack()  to stack along rows.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [72]:
# vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [73]:
# dstack() to stack along height
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [74]:
# array_split()
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [75]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr.shape)

(6, 2)


In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [77]:
## sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [78]:
## sorting string
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [79]:
# sorting 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [80]:
## filter array that will return only values higher than 42

arr=np.array([42,41,52,2,56,46])

filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, False, True, True]
[52 56 46]


In [81]:
# filter array that will return only even elements

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array

In [82]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [84]:
from numpy import random
x = random.randint(100)
print(x)

56
