<a href="https://colab.research.google.com/github/sevensixteeeen/NumPy-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# indexing
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,0])

7


In [ ]:
#slicing
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
# From the second element, slice elements from index 0 to index 3 (not included):
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:3])

[6 7 8]


In [ ]:
#from both element, return index 2;
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6 7]
int32


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# randam decimal number
np.random.rand(4,2,3)

array([[[0.85372851, 0.03554887, 0.81189754],
        [0.96148837, 0.8039149 , 0.25000255]],

       [[0.33122718, 0.29213763, 0.46409414],
        [0.49295848, 0.30416851, 0.18212314]],

       [[0.43043396, 0.90104886, 0.25192231],
        [0.97443439, 0.07806891, 0.47503411]],

       [[0.85960999, 0.31107265, 0.45716304],
        [0.25469434, 0.44416419, 0.23987566]]])

In [ ]:
# randam integer number
np.random.randint(7,9,size=[3,6])

array([[8, 7, 8, 7, 8, 7],
       [8, 7, 8, 8, 7, 7],
       [7, 7, 8, 8, 8, 8]])

In [ ]:
np.random.randint(7,9)

8

In [ ]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat on array
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
op = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
op[1:4,1:4]=z
print(op)
print(op.ndim)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
2


In [ ]:
# three dimension
arr =np.array ([[1,2,3],[4,5,6]],[[7,8,9],[1,11,12]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 1 11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# dimension of an array
arr_1d = np.array([1, 2, 3])
print(f"Dimension of arr_1d: {arr_1d.ndim}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimension of arr_2d: {arr_2d.ndim}")

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr_3d: {arr_3d.ndim}")

Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3


In [ ]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array:",arr.shape)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(2,3,2)
print(narr)
print("dimension ",narr.ndim,"from ",arr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimension  3 from  1


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],)
print(arr,"dimension of an array=",arr.ndim)
narr = arr.reshape(6,5)
print(narr)
narr[[0,4,5],3:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] dimension of an array= 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")
for x in np.nditer(arr[:, ::2]):
  print(x)

Dimension of arr: 2
Shape of arr: (2, 4)
1
3
5
7


In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


## practicing python function

In [ ]:
# basic function
def greet():
  print("hello")

greet()

hello


In [ ]:
# function with parameter

def add_fun(a, b):
  return a + b

def sub_fun(a, b):
  return a - b

a = int(input("enter the 1st no."))
b = int(input("enter the 2st no."))
print(add_fun(a, b))
# You can also call sub_fun like this:
print("subtraction of given no.",sub_fun(a, b))

enter the 1st no.12
enter the 2st no.6
18
subtraction of given no. 6
