<a href="https://colab.research.google.com/github/sevensixteeeen/NumPy-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# indexing
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,0])

7


In [3]:
#slicing
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [5]:
# From the second element, slice elements from index 0 to index 3 (not included):
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:3])

[6 7 8]


In [6]:
#from both element, return index 2;
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [7]:
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [59]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1,2,3,4,5,6,7])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6 7]
int32


In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [11]:
# randam decimal number
np.random.rand(4,2,3)

array([[[0.57734628, 0.53188475, 0.00304969],
        [0.19717846, 0.64837001, 0.01892295]],

       [[0.47694689, 0.47222712, 0.7120503 ],
        [0.09681933, 0.51642316, 0.35862644]],

       [[0.27175449, 0.34882441, 0.74577398],
        [0.06188156, 0.10510356, 0.19961277]],

       [[0.81895843, 0.16257349, 0.24071438],
        [0.86531061, 0.64639689, 0.64062817]]])

In [12]:
# randam integer number
np.random.randint(7,9,size=[3,6])

array([[8, 8, 7, 7, 8, 8],
       [7, 7, 7, 7, 8, 7],
       [8, 7, 8, 7, 7, 8]])

In [13]:
np.random.randint(7,9)

7

In [14]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# repeat on array
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [16]:
op = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
op[1:4,1:4]=z
print(op)
print(op.ndim)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
2


In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

3


In [18]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [19]:
# dimension of an array
arr_1d = np.array([1, 2, 3])
print(f"Dimension of arr_1d: {arr_1d.ndim}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimension of arr_2d: {arr_2d.ndim}")

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr_3d: {arr_3d.ndim}")

Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3


In [20]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array:",arr.shape)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
narr = arr.reshape(2,3,2)
print(narr)
print("dimension ",narr.ndim,"from ",arr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimension  3 from  1


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],)
print(arr,"dimension of an array=",arr.ndim)
narr = arr.reshape(6,5)
print(narr)
narr[[0,4,5],3:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] dimension of an array= 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [23]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [24]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [26]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [27]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")
for x in np.nditer(arr[:, ::2]):
  print(x)

Dimension of arr: 2
Shape of arr: (2, 4)
1
3
5
7


In [29]:
# vstack()  to stack along rows.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [30]:
# vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [31]:
# dstack() to stack along height
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [32]:
# array_split()
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr.shape)

(6, 2)


In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [35]:
## sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [36]:
## sorting string
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [37]:
# sorting 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [38]:
## filter array that will return only values higher than 42

arr=np.array([42,41,52,2,56,46])

filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, False, True, True]
[52 56 46]


In [39]:
# filter array that will return only even elements

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array

In [40]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [42]:
## random integer from 1 to 100:
from numpy import random
x = random.randint(100)
print(x)

78


In [43]:
## random float from 0 to 1:
from numpy import random
x=random.rand()
print(x)

0.880177288874791


In [44]:
## 1-D array containing 5 random integers from 0 to 100:
x=random.randint(0,100,size=5)
print(x)

[33 82 49 74 68]


In [45]:
## 2D  array
x=random.randint(0,100,size=(3,5))
print(x)

[[61 87 99 76  2]
 [58 47 37 95 22]
 [51 99 51 41 11]]


In [63]:
## 3-D array
x=random.randint(0,100,size=(3,4,6))
print(x)
print("demintion of a array",x.ndim)

[[[23 67 67 85 49 16]
  [51 92 50 61 96 12]
  [53 27 69 59 31 85]
  [67 26 47 77 29 66]]

 [[52 44 76 88 64 48]
  [59 60 10 91 44 35]
  [74 95 38 47 83 50]
  [79 39 99 55 37 85]]

 [[36 82 76 97 49 22]
  [64 40 11 88 91  8]
  [61 95 62 71  0 11]
  [78 78 39 55 41 47]]]
demintion of a array 3


In [46]:
## 1-D array containing 5 random floats:
x=random.rand(5)
print(x)

[0.09085405 0.52636064 0.52490617 0.6517065  0.10732433]


In [50]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[5 7 7 5 7 7 5 7 5 5 7 5 7 5 5 7 7 7 5 5 7 5 7 7 5 5 7 7 3 3 7 3 7 5 5 7 5
 5 3 7 7 7 5 7 7 7 7 3 7 7 5 7 7 5 7 7 5 7 7 7 7 3 7 7 7 7 7 3 5 7 7 7 7 5
 7 5 3 7 7 3 5 7 5 5 5 7 7 7 7 7 7 7 7 7 7 3 7 7 5 5]
